DROP TABLE IF EXISTS Student;
 
CREATE TABLE Student (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  User_Name VARCHAR(50) NOT NULL UNIQUE,
  First_Name VARCHAR(50) NOT NULL,
  Last_Name VARCHAR(50) NOT NULL,
  Email_ID VARCHAR(50) NOT NULL,
  Role VARCHAR(50) NOT NULL,
  SSN VARCHAR(50) NOT NULL UNIQUE
);